server:
  port: 8083

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/bankofgeorgia?authSource=admin

logging:
  level:
    com.bankofgeorgia: DEBUG
